FROM python:3.10-slim

WORKDIR /app

RUN apt-get update
RUN apt-get install -y gnupg wget curl unzip --no-install-recommends
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 
RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list 
RUN apt-get update -y
RUN apt-get install -y google-chrome-stable

RUN apt-get install -y xclip xvfb
ENV DISPLAY=:99
RUN nohup bash -c "xvfb :99 -screen 0 1280x720x16 &"


COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
RUN pip install "flask[async]"

COPY . .

EXPOSE 3002

CMD python server.py run